version: 0.0.{build}
os: Visual Studio 2017
    
build:
  project: MitchGame.sln
  parallel: true
  verbosity: normal
branches:
  only:
    - master
environment:
  matrix:
  - env_renderdoc_path: "https://renderdoc.org/stable/1.2/RenderDoc_1.2_64.msi"

install:
- ps: >-
    if ($Env:env_renderdoc_path) {
      md _tmp
      cd _tmp
      Start-FileDownload $Env:env_renderdoc_path "RenderDoc.msi"
      Start-Process -FilePath "RenderDoc.msi" /S -Wait
      cd ../
    }
before_build:
  - git submodule init
  - git submodule update
  - cd Engine
  - git submodule init
  - git submodule update
  - cd ../
  - ./GenerateSolution.bat
  - ./CopyAssets.bat
  - cd Engine/ThirdParty
  - ./GenerateSolutions.bat
  - cd ../../
  - nuget restore
after_build:
  - mkdir _Artifacts
  - xcopy /y /d /s Build\%CONFIGURATION%\Assets _Artifacts\Assets\
  - xcopy /y /d %APPVEYOR_BUILD_FOLDER%\Build\%CONFIGURATION%\*.dll %APPVEYOR_BUILD_FOLDER%\_Artifacts
  - xcopy /y /d %APPVEYOR_BUILD_FOLDER%\Build\%CONFIGURATION%\*.exe %APPVEYOR_BUILD_FOLDER%\_Artifacts
  - 7z a %APPVEYOR_BUILD_FOLDER%\MitchGame_%APPVEYOR_REPO_BRANCH%_%APPVEYOR_BUILD_VERSION%_%CONFIGURATION%.zip _Artifacts